/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.espe.edu.rolepaymentsystem.view;

import ec.espe.edu.rolepaymentsystem.controller.EmployeeManager;
import ec.espe.edu.rolepaymentsystem.model.Employee;
import ec.espe.edu.rolepaymentsystem.util.Calculator;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.Calendar;

public class FrmAnnualPayrollReport extends javax.swing.JFrame {
    private final EmployeeManager employeeManager;
    private DefaultPieDataset dataset;
    private JFreeChart chart;
    private ChartPanel chartPanel;

    public FrmAnnualPayrollReport(EmployeeManager employeeManager) {
        initComponents();
        this.employeeManager = employeeManager;
        dataset = new DefaultPieDataset();
        initializeChart();
        setupYearChooser();
        updateChart();
    }

    private void initializeChart() {
        chart = ChartFactory.createPieChart(
            "Reporte Anual de Nómina",
            dataset,
            true,
            true,
            false
        );

        chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(600, 400));
        PanelGrafich.setLayout(new BorderLayout());
        PanelGrafich.add(chartPanel, BorderLayout.CENTER);
    }

    private void setupYearChooser() {
        jYears.addPropertyChangeListener("year", evt -> updateChart());
    }

private void updateChart() {
    int selectedYear = jYears.getYear();
    List<Employee> employees = employeeManager.getEmployees();
    dataset.clear();
    double totalIncome = 0;
    double totalDeductions = 0;
    double totalNetPayment = 0;
    boolean dataFound = false;
    Calculator calculator = new Calculator();
    Calendar cal = Calendar.getInstance();

    for (Employee emp : employees) {
        cal.setTime(emp.getHireDate());
        int hireYear = cal.get(Calendar.YEAR);

        if (hireYear == selectedYear) {
            double overtimePayment = calculator.calculateOvertimeHours(emp.getOvertimeHours(), 40, emp.getBasicSalary() / 160);
            double reserveFunds = calculator.calculateReserveFunds(emp.getBasicSalary());
            double totalEmployeeIncome = calculator.calculateTotalIncome(emp.getBasicSalary(), overtimePayment, emp.getBonuses());
            double iessContribution = calculator.calculateIessContribution(totalEmployeeIncome, reserveFunds);
            double biweeklyAdvance = calculator.calculateBiweeklyAdvance(emp.getBasicSalary());
            double totalExpenses = calculator.calculateTotalExpenses(iessContribution, biweeklyAdvance, emp.getIessLoans(), emp.getCompanyLoans(), emp.getFines(), calculator.calculateFoodDeduction(emp.getBringOwnFood(), 50));
            double netPayment = calculator.calculateNetPayment(totalEmployeeIncome, totalExpenses);
            double Deductions = calculator.calculateTotalDeductions(emp);

            totalIncome += totalEmployeeIncome;
            totalDeductions += Deductions;
            totalNetPayment += netPayment;

            dataFound = true;
        }
    }

    if (!dataFound) {
        totalIncome = 0;
        totalDeductions = 0;
        totalNetPayment = 0;
    }

    dataset.setValue("Ingresos Totales", totalIncome);
    dataset.setValue("Deducciones Totales", totalDeductions);
    dataset.setValue("Pago Neto Total", totalNetPayment);
    chart.fireChartChanged();
    PanelGrafich.revalidate();
    PanelGrafich.repaint();

    if (!dataFound) {
        JOptionPane.showMessageDialog(this, "No hay datos para el año " + selectedYear, "Sin datos", JOptionPane.INFORMATION_MESSAGE);
    }
}


     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtIniciarSesion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jYears = new com.toedter.calendar.JYearChooser();
        PanelGrafich = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        txtIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtIniciarSesion.setText("Informe Anual de Nómina");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(txtIniciarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtIniciarSesion)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setText("Año:");

        javax.swing.GroupLayout PanelGrafichLayout = new javax.swing.GroupLayout(PanelGrafich);
        PanelGrafich.setLayout(PanelGrafichLayout);
        PanelGrafichLayout.setHorizontalGroup(
            PanelGrafichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        PanelGrafichLayout.setVerticalGroup(
            PanelGrafichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 344, Short.MAX_VALUE)
        );

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(PanelGrafich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btnBack)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGrafich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(btnBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if(true){//read users from database and compare used nameand
            FrmRolePaymentSystem frmRolePaymentSystem=new FrmRolePaymentSystem();
            this.setVisible(false);
            frmRolePaymentSystem.setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAnnualPayrollReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAnnualPayrollReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAnnualPayrollReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAnnualPayrollReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmployeeManager employeeManager=new EmployeeManager();
                FrmAnnualPayrollReport frmAnnualPayrollReport= new FrmAnnualPayrollReport(employeeManager);
                frmAnnualPayrollReport.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGrafich;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JYearChooser jYears;
    private javax.swing.JLabel txtIniciarSesion;
    // End of variables declaration//GEN-END:variables
}
