/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.espe.edu.rolepaymentsystem.view;

import ec.espe.edu.rolepaymentsystem.model.Employee;
import java.util.Date;
import javax.swing.JOptionPane;
import ec.espe.edu.rolepaymentsystem.util.Validations;
import ec.espe.edu.rolepaymentsystem.controller.EmployeeManager;
import ec.espe.edu.rolepaymentsystem.model.EmployeePaymentDetails;
import ec.espe.edu.rolepaymentsystem.util.Calculator;
import ec.espe.edu.rolepaymentsystem.util.EmployeeToMongo;
import ec.espe.edu.rolepaymentsystem.util.SaveManager;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;

/**
 *
 * @author Code Masters
 */
public class FrmAddEmployee extends javax.swing.JFrame {
    private final FrmAllEmployee allEmployeeForm;
    private final EmployeeManager employeeManager;
    private final Calculator calculator;
    Validations validations=new Validations();
    SaveManager saveManager;
    /**
     * Creates new form FrmBusqueda9noDigito
     * @param allEmployeeForm
     */
    public FrmAddEmployee(FrmAllEmployee allEmployeeForm) {
    initComponents();
    this.saveManager = new SaveManager();
    this.allEmployeeForm = allEmployeeForm;
    this.employeeManager = allEmployeeForm.getEmployeeManager();
    this.calculator = new Calculator();
    validations.addKeyListener(txtName, true);
    validations.addKeyListener(txtLastname, true);
    validations.addKeyListener(txtOvertimeHours, false);
    validations.addKeyListener(txtAbsentDays, false);
    validations.addKeyListener(txtBonuses, false);
    validations.addKeyListener(txtIessLoans, false);
    validations.addKeyListener(txtCompanyLoans, false);
    validations.addKeyListener(txtFines, false);
    txtId.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
              validations.isValidId(txtId.getText());
            }
        });
    }
    private void clearFields() {
    txtName.setText("");
    txtLastname.setText("");
    txtId.setText("");
    txtOvertimeHours.setText("");
    txtAbsentDays.setText("");
    txtBonuses.setText("");
    txtIessLoans.setText("");
    txtCompanyLoans.setText("");
    txtFines.setText("");
    cmbBringOwnFood.setSelectedIndex(0); 
    jDateEmployee.setDate(null);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCompanyLoans = new javax.swing.JTextField();
        txtIessLoans = new javax.swing.JTextField();
        txtBonuses = new javax.swing.JTextField();
        txtFines = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbBringOwnFood = new javax.swing.JComboBox<>();
        btnRegisterEmployee = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAbsentDays = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtOvertimeHours = new javax.swing.JTextField();
        jDateEmployee = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Numero de identificacion:");

        txtName.setText("Yostin");
        txtName.setToolTipText("Solo se permiten caracteres.No se permiten numeros ni caracteres especiales como *.#");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtLastname.setText("Sisalema");
        txtLastname.setToolTipText("Solo se permiten caracteres.No se permiten numeros ni caracteres especiales como *.#");
        txtLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastnameActionPerformed(evt);
            }
        });

        txtId.setText("1414114814");
        txtId.setToolTipText("Ingrese dos letras seguidos de números. Ejemplo: LO123456789. No se permiten letras ni caracteres especiales como *.#");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Empleado");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel5.setText("Fecha de contratacion:");

        jLabel6.setText("Horas Extras:");

        jLabel7.setText("Bonificaciones:");

        jLabel8.setText("Préstamos IESS:");

        jLabel9.setText("Dias Ausentes:");

        jLabel10.setText("Multas:");

        txtCompanyLoans.setText("1");
        txtCompanyLoans.setToolTipText("No se permiten letras, espacios ni caracteres especiales como *.#");
        txtCompanyLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyLoansActionPerformed(evt);
            }
        });

        txtIessLoans.setText("14");
        txtIessLoans.setToolTipText("No se permiten letras, espacios ni caracteres especiales como *.#");
        txtIessLoans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIessLoansActionPerformed(evt);
            }
        });

        txtBonuses.setText("1121");
        txtBonuses.setToolTipText("No se permiten letras, espacios ni caracteres especiales como *.#");
        txtBonuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBonusesActionPerformed(evt);
            }
        });

        txtFines.setText("8");
        txtFines.setToolTipText("No se permiten letras, espacios ni caracteres especiales como *.#");
        txtFines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinesActionPerformed(evt);
            }
        });

        jLabel11.setText("¿Trae su propia comida?");

        cmbBringOwnFood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cmbBringOwnFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBringOwnFoodActionPerformed(evt);
            }
        });

        btnRegisterEmployee.setBackground(new java.awt.Color(0, 153, 153));
        btnRegisterEmployee.setText("Registrar Empleado");
        btnRegisterEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterEmployeeActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Atrás");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 204, 153));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Otros Datos: ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Información Financiera:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addGap(146, 146, 146)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        txtAbsentDays.setText("4");
        txtAbsentDays.setToolTipText("No se permiten letras, espacios ni caracteres especiales como *.#");

        jLabel14.setText("Préstamos de Empresa:");

        txtOvertimeHours.setText("1");
        txtOvertimeHours.setToolTipText("No se permiten letras, espacios ni caracteres especiales como *.#");
        txtOvertimeHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOvertimeHoursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(97, 97, 97)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId)))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jDateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(btnRegisterEmployee)
                                .addGap(9, 9, 9)
                                .addComponent(btnBack))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAbsentDays, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBringOwnFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFines, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(txtBonuses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIessLoans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(60, 60, 60)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOvertimeHours, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompanyLoans, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 290, Short.MAX_VALUE)))
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtOvertimeHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtAbsentDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtCompanyLoans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cmbBringOwnFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBonuses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIessLoans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnRegisterEmployee))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastnameActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnRegisterEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterEmployeeActionPerformed
    EmployeeToMongo employeeToMongo=new EmployeeToMongo();
    List<Employee> employees = employeeManager.getEmployees();
    Calculator calculator = new Calculator();
    Employee employee;
    boolean isValid = true;
    StringBuilder errorMessage = new StringBuilder("Error: Los siguientes campos son inválidos o están vacíos:\n");

    String name = "";
    String lastName = "";
    String idNumber = "";
    double basicSalary=460;
    double overtimeHours = 0;
    double absentDays = 0;
    double bonuses = 0;
    double iessLoans = 0;
    double companyLoans = 0;
    double fines = 0;
    boolean bringOwnFood =true;
    
    // Validate string inputs
    if (!validations.getStringInput(txtName.getText())) {
        isValid = false;
        errorMessage.append("- Nombre\n");
    }
    if (!validations.getStringInput(txtLastname.getText())) {
        isValid = false;
        errorMessage.append("- Apellido\n");
    }

    // Validate ID
    if (!validations.isValidId(txtId.getText())) {
        isValid = false;
        errorMessage.append("- Número de identificación\n");
    }

    // Validate numeric inputs
    String[] numericFields = {txtOvertimeHours.getText(), txtAbsentDays.getText(), txtBonuses.getText(), 
                              txtIessLoans.getText(), txtCompanyLoans.getText(), txtFines.getText()};
    String[] fieldNames = {"Horas extras", "Días ausentes", "Bonificaciones", "Préstamos IESS", 
                           "Préstamos de empresa", "Multas"};
    
    for (int i = 0; i < numericFields.length; i++) {
        if (!validations.getDoubleInput(numericFields[i])) {
            isValid = false;
            errorMessage.append("- ").append(fieldNames[i]).append("\n");
        }
    }

    // Validate date
    Date hireDate = jDateEmployee.getDate();
    if (hireDate == null) {
        isValid = false;
        errorMessage.append("- Fecha de contratación\n");
    }

    if (!isValid) {
        JOptionPane.showMessageDialog(this, errorMessage.toString(), "Error de validación", JOptionPane.ERROR_MESSAGE);
        return;
    }
        name = txtName.getText();
        lastName = txtLastname.getText();
        idNumber = txtId.getText();
        hireDate = jDateEmployee.getDate();
        overtimeHours = Double.parseDouble(txtOvertimeHours.getText());
        absentDays = Double.parseDouble(txtAbsentDays.getText());
        bonuses = Double.parseDouble(txtBonuses.getText());
        iessLoans = Double.parseDouble(txtIessLoans.getText());
        companyLoans = Double.parseDouble(txtCompanyLoans.getText());
        fines = Double.parseDouble(txtFines.getText());
        bringOwnFood = cmbBringOwnFood.getSelectedItem().toString().equals("Si");
        
        double overtimePayment = calculator.calculateOvertimeHours(overtimeHours, 40, basicSalary / 160); 
        double reserveFunds = calculator.calculateReserveFunds(basicSalary);
        double totalIncome = calculator.calculateTotalIncome(basicSalary, overtimePayment, bonuses);
        double iessContribution = calculator.calculateIessContribution(totalIncome, reserveFunds);
        double biweeklyAdvance = calculator.calculateBiweeklyAdvance(basicSalary);
        double foodDeduction = calculator.calculateFoodDeduction(bringOwnFood, 50); 
        double totalExpenses = calculator.calculateTotalExpenses(iessContribution, biweeklyAdvance, iessLoans, companyLoans, fines, foodDeduction);
        double netPayment = calculator.calculateNetPayment(totalIncome, totalExpenses);
        double employerContribution = calculator.calculateEmployerContribution(totalIncome, reserveFunds);
        double totalEmployeeCost = calculator.calculateTotalEmployeeCost(netPayment, employerContribution);

        EmployeePaymentDetails paymentDetails = new EmployeePaymentDetails(overtimePayment, reserveFunds, totalIncome, iessContribution, biweeklyAdvance, foodDeduction, totalExpenses, netPayment, employerContribution, totalEmployeeCost);

        employee = new Employee(name, lastName, idNumber, hireDate, 460, overtimeHours, absentDays, bonuses, iessLoans, companyLoans, fines, bringOwnFood);
        JOptionPane.showMessageDialog(this, "Se registró el empleado --> " + employee.getName() + " " + employee.getLastName(), "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        employeeManager.addEmployee(employee);
        saveManager.saveEmployees(employeeManager.getEmployees()); 
        allEmployeeForm.updateTable();
        employeeToMongo.uploadEmployeeData(employee,paymentDetails);
        clearFields();
    }//GEN-LAST:event_btnRegisterEmployeeActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if(true){//read users from database and compare used nameand 
        FrmRolePaymentSystem frmRolePaymentSystem=new FrmRolePaymentSystem(); 
        this.setVisible(false); 
        frmRolePaymentSystem.setVisible(true);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCompanyLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyLoansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyLoansActionPerformed

    private void txtIessLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIessLoansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIessLoansActionPerformed

    private void txtBonusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBonusesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBonusesActionPerformed

    private void txtFinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinesActionPerformed

    private void txtOvertimeHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOvertimeHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOvertimeHoursActionPerformed

    private void cmbBringOwnFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBringOwnFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBringOwnFoodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAllEmployee frmAllEmployee = new FrmAllEmployee();
                FrmAddEmployee frmAddEmployee= new FrmAddEmployee(frmAllEmployee);
                frmAddEmployee.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegisterEmployee;
    private javax.swing.JComboBox<String> cmbBringOwnFood;
    private com.toedter.calendar.JDateChooser jDateEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtAbsentDays;
    private javax.swing.JTextField txtBonuses;
    private javax.swing.JTextField txtCompanyLoans;
    private javax.swing.JTextField txtFines;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIessLoans;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOvertimeHours;
    // End of variables declaration//GEN-END:variables
}
